#!/bin/bash

rosbag record -O CAST-launch-50psi-transition-5.bag \
/diagnostics \
/gyro/reset \
/gyro/quaternion \
/mavlink/from \
/mavlink/gcs_ip \
/mavlink/to \
/mavros/adsb/send \
/mavros/adsb/vehicle \
/mavros/battery \
/mavros/cam_imu_sync/cam_imu_stamp \
/mavros/camera/image_captured \
/mavros/cellular_status/status \
/mavros/companion_process/status \
/mavros/distance_sensor/rangefinder_pub \
/mavros/distance_sensor/rangefinder_sub \
/mavros/esc_info \
/mavros/esc_status \
/mavros/esc_telemetry \
/mavros/estimator_status \
/mavros/extended_state \
/mavros/fake_gps/mocap/pose \
/mavros/geofence/waypoints \
/mavros/global_position/compass_hdg \
/mavros/global_position/global \
/mavros/global_position/gp_lp_offset \
/mavros/global_position/gp_origin \
/mavros/global_position/local \
/mavros/global_position/raw/fix \
/mavros/global_position/raw/gps_vel \
/mavros/global_position/raw/satellites \
/mavros/global_position/rel_alt \
/mavros/global_position/set_gp_origin \
/mavros/gps_input/gps_input \
/mavros/gps_rtk/rtk_baseline \
/mavros/gps_rtk/send_rtcm \
/mavros/gpsstatus/gps1/raw \
/mavros/gpsstatus/gps1/rtk \
/mavros/gpsstatus/gps2/raw \
/mavros/gpsstatus/gps2/rtk \
/mavros/home_position/home \
/mavros/home_position/set \
/mavros/imu/data \
/mavros/imu/data_raw \
/mavros/imu/data_corrected \
/mavros/imu/diff_pressure \
/mavros/imu/mag \
/mavros/imu/static_pressure \
/mavros/imu/temperature_baro \
/mavros/imu/temperature_imu \
/mavros/landing_target/lt_marker \
/mavros/landing_target/pose \
/mavros/landing_target/pose_in \
/mavros/local_position/accel \
/mavros/local_position/odom \
/mavros/local_position/pose \
/mavros/local_position/pose_cov \
/mavros/local_position/velocity_body \
/mavros/local_position/velocity_body_cov \
/mavros/local_position/velocity_local \
/mavros/log_transfer/raw/log_data \
/mavros/log_transfer/raw/log_entry \
/mavros/mag_calibration/report \
/mavros/mag_calibration/status \
/mavros/manual_control/control \
/mavros/manual_control/send \
/mavros/mission/reached \
/mavros/mission/waypoints \
/mavros/mocap/pose \
/mavros/mount_control/command \
/mavros/mount_control/orientation \
/mavros/mount_control/status \
/mavros/nav_controller_output \
/mavros/obstacle/send \
/mavros/odometry/in \
/mavros/odometry/out \
/mavros/onboard_computer/status \
/mavros/param/param_value \
/mavros/play_tune \
/mavros/radio_status \
/mavros/rallypoint/waypoints \
/mavros/rangefinder/rangefinder \
/mavros/rc/in \
/mavros/rc/out \
/mavros/rc/override \
/mavros/setpoint_accel/accel \
/mavros/setpoint_attitude/cmd_vel \
/mavros/setpoint_attitude/thrust \
/mavros/setpoint_position/global \
/mavros/setpoint_position/global_to_local \
/mavros/setpoint_position/local \
/mavros/setpoint_raw/attitude \
/mavros/setpoint_raw/global \
/mavros/setpoint_raw/local \
/mavros/setpoint_raw/target_attitude \
/mavros/setpoint_raw/target_global \
/mavros/setpoint_raw/target_local \
/mavros/setpoint_trajectory/desired \
/mavros/setpoint_trajectory/local \
/mavros/setpoint_velocity/cmd_vel \
/mavros/setpoint_velocity/cmd_vel_unstamped \
/mavros/state \
/mavros/statustext/recv \
/mavros/statustext/send \
/mavros/sys_status \
/mavros/terrain/report \
/mavros/time_reference \
/mavros/timesync_status \
/mavros/trajectory/desired \
/mavros/trajectory/generated \
/mavros/trajectory/path \
/mavros/tunnel/in \
/mavros/tunnel/out \
/mavros/vfr_hud \
/mavros/vision_pose/pose \
/mavros/vision_pose/pose_cov \
/mavros/wind_estimation \
/optitrack/vrpn_client_node/SQUID/pose \
/camera_down/image_raw \
/down/ov_msckf/odomimu \
/down/ov_msckf/pathgt \
/down/ov_msckf/pathimu \
/down/ov_msckf/points_aruco \
/down/ov_msckf/points_msckf \
/down/ov_msckf/points_sim \
/down/ov_msckf/points_slam \
/down/ov_msckf/posegt \
/down/ov_msckf/poseimu \
/down/ov_msckf/trackhist \
/right/ov_msckf/odomimu \
/right/ov_msckf/pathgt \
/right/ov_msckf/pathimu \
/right/ov_msckf/points_aruco \
/right/ov_msckf/points_msckf \
/right/ov_msckf/points_sim \
/right/ov_msckf/points_slam \
/right/ov_msckf/posegt \
/right/ov_msckf/poseimu \
/right/ov_msckf/trackhist \
/left/ov_msckf/odomimu \
/left/ov_msckf/pathgt \
/left/ov_msckf/pathimu \
/left/ov_msckf/points_aruco \
/left/ov_msckf/points_msckf \
/left/ov_msckf/points_sim \
/left/ov_msckf/points_slam \
/left/ov_msckf/posegt \
/left/ov_msckf/poseimu \
/left/ov_msckf/trackhist \
/stereo/ov_msckf/odomimu \
/stereo/ov_msckf/pathgt \
/stereo/ov_msckf/pathimu \
/stereo/ov_msckf/points_aruco \
/stereo/ov_msckf/points_msckf \
/stereo/ov_msckf/points_sim \
/stereo/ov_msckf/points_slam \
/stereo/ov_msckf/posegt \
/stereo/ov_msckf/poseimu \
/stereo/ov_msckf/trackhist \
/rosout \
/rosout_agg \
/tf \
/tf_static
